import "./globals.css";
import { ContractProvider } from "../hooks/useContract";
import { GameStateProvider } from "@/hooks/useGameState";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
  },
  // You can add more metadata fields here
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ContractProvider>
          <GameStateProvider>{children}</GameStateProvider>
        </ContractProvider>
      </body>
    </html>
  );
}
